// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Annotator.Plugin.Auth = (function(_super) {
    __extends(Auth, _super);

    Auth.prototype.options = {
      token: null
    };

    function Auth(element, options) {
      Auth.__super__.constructor.apply(this, arguments);
      this.setToken(this.options.token);
    }

    Auth.prototype.setToken = function(token) {
      console.log("Returning a token", this.token);
      return this.token = token;
    };

    Auth.prototype.updateHeaders = function() {
      var current;
      current = this.element.data('annotator:headers');
      return this.element.data('annotator:headers', $.extend(current, {
        'Authorization': "Bearer " + this.token
      }));
    };

    Auth.prototype.withToken = function(callback) {
      if (callback != null) {
        return callback(this.token);
      }
    };

    return Auth;

  })(Annotator.Plugin);

}).call(this);
